# SPDX-License-Identifier: GPL-2.0
# IPXLAT - Stateless IP/ICMP Translation (SIIT) virtual device driver
#
# Copyright (C) 2026- Mandelbit SRL
# Copyright (C) 2026- Daniel Gröber <dxld@darkboxed.org>
#
#  Author:	Antonio Quartulli <antonio@mandelbit.com>
#		Daniel Gröber <dxld@darkboxed.org>
#		Ralf Lici <ralf@mandelbit.com>

TEST_PROGS := \
	ipxlat_data.sh \
	ipxlat_frag.sh \
	ipxlat_icmp_err.sh \
# end of TEST_PROGS

TEST_FILES := \
	ipxlat_lib.sh \
# end of TEST_FILES

TEST_GEN_FILES := \
	ipxlat_udp4_zero_csum_send \
# end of TEST_GEN_FILES

include ../../lib.mk
