# SPDX-License-Identifier: GPL-2.0
# IPXLAT - Stateless IP/ICMP Translation virtual device driver
#
# Copyright (C) 2024- Alberto Leiva Popper <ydahhrk@gmail.com>
# Copyright (C) 2026- Mandelbit, SRL
#
#  Author:	Alberto Leiva Popper <ydahhrk@gmail.com>
#		Antonio Quartulli <antonio@mandelbit.com>
#		Ralf Lici <ralf@mandelbit.com>

TEST_PROGS := \
	ipxlat_data.sh \
	ipxlat_frag.sh \
	ipxlat_icmp_err.sh \
# end of TEST_PROGS

TEST_FILES := \
	ipxlat_lib.sh \
# end of TEST_FILES

include ../../lib.mk
