# SPDX-License-Identifier: GPL-2.0
#
# JOOLIF - Stateless IP/ICMP Translation (SIIT) virtual device driver
#
# Copyright (C) 2024- Alberto Leiva Popper <ydahhrk@gmail.com>
# Copyright (C) 2025- Antonio Quartulli <antonio@mandelbit.com>

obj-$(CONFIG_JOOLIF) := joolif.o

joolif-objs += main.o
joolif-objs += rfc7915.o
joolif-objs += address.o
joolif-objs += ipv6_hdr_iterator.o
joolif-objs += packet.o
joolif-objs += translation_state.o
