# SPDX-License-Identifier: GPL-2.0
#
# IPXLAT - Stateless IP/ICMP Translation (SIIT) virtual device driver

obj-$(CONFIG_IPXLAT) := ipxlat.o

ipxlat-objs += main.o
ipxlat-objs += address.o
ipxlat-objs += packet.o
ipxlat-objs += transport.o
ipxlat-objs += dispatch.o
ipxlat-objs += translate_46.o
ipxlat-objs += translate_64.o
ipxlat-objs += icmp_46.o
ipxlat-objs += icmp_64.o
